# Configure Jitpack build options (https://jitpack.io/)
# Jitpack is currently offered due to lack of Maven Central packaging
# such that clients can depend on Mochalog
# In future, Mochalog releases will be directly available via
# Maven Central and Jitpack dependency will no long be necessary

jdk:
    - oraclejdk8

