# Perform CI in a Java environment
language: java

jdk:
    - oraclejdk8

env:
    global:
        # Set SWI-Prolog environment variables
        - SWIPL_VERSION="7.6.4"
        - SWI_HOME_DIR="/usr/local/lib/swipl-$SWIPL_VERSION"

before_install:
    # Ensure SWI-Prolog is downloaded/built on to the build server
    - sudo thirdparty/swi-prolog/swipl-install.sh $SWIPL_VERSION
    # Ensure external shared libraries are capable of being dynamically loaded
    - export LD_PRELOAD="$SWI_HOME_DIR/lib/x86_64-linux/libswipl.so.$SWIPL_VERSION"
    - export LD_LIBRARY_PATH="$SWI_HOME_DIR/lib/x86_64-linux/"
    - export PATH=$PATH:$SWI_HOME_DIR/bin/x86_64-linux/
